Hello Microverse Project Pull Request
ezraermy/hello_microverse pull request #1
Opened 2022-10-25 20:14 UTC by ezraermy

2022-10-25 21:42 UTC, sajid-munawar requested changes
# Changes Required 
 ### Hi @HunterX-7 ,
 Nice job, you are almost there.
 
 ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
 
 ## (Highlights) Good Points: 
 * Followed Github flow :heavy_check_mark:

 ## (Changes Required) Aspects to improve: 
 *  ### Please do the following:
- [x] Please kindly add a more descriptive PR title.
 See a demo below:

https://user-images.githubusercontent.com/52934128/176308229-e31b2c8d-110b-4823-a2a8-31c1b7d7c73d.mp4

- [ ] I kindly suggest that you add a more descriptive PR title and description. 
## EXAMPLE
```
## Hello World
In this Pull Request, I:
- Created branches with different base branches.
- Followed GitHub flow.
- Added a descriptive and easy to understand README
- Added a HTML file
- Added a CSS File
- Added a h1 text of "Hello-World"
```


- [x] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

- [x] I suggest you kindly add a [README](https://github.com/microverseinc/readme-template) file to your repo, using the Microverse [template](https://github.com/microverseinc/readme-template) as this will give users detailed information about your project. please customize it as your details. Here is demo below

https://user-images.githubusercontent.com/52934128/176309876-98f49c4e-3e62-4edd-9bf3-51a66f48e2cd.mp4


 ## [Optional] suggestions:
 * Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding! :clap::clap::clap:**

> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @sajid-munawar in your question so I can receive the notification.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-25 22:46 UTC, mckent05 approved these changes
Hi @ezraermy,

# STATUS: APPROVED ✔️ ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- GitHub flow correctly used 👍 
- All linter checks are passing correctly ✔️ ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 20:06 UTC, AbayomiOlaoye requested changes
Hi @ezraermy :wave:, 

Good job so far!
There are some minor issues that you still need to work on to go to the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211648453-972385c1-ad46-4ee7-9097-83002716c363.gif)

## Highlights
- Descriptive commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 
- Proper GitHub flow :heavy_check_mark: 
- Descriptive Pull Request :heavy_check_mark: 
- Great implementation :heavy_check_mark: 

## Required Changes ♻️
- [ ] While this project has been approved before now, due to the recent changes in [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md), it appears that there are a few issues with the ReadMe file:
- Kindly consider using the newly approved [ReadMe Template](https://github.com/microverseinc/readme-template) for your project and remember to make the content as custom and personalized as it can be. This will enhance the professional look o your work, improves readability, and show that you have eyes for details.
- Your `ReadMe` file is presently not in the `branch` where you are making the request. Please kindly include the updates of the [ReadMe](https://github.com/microverseinc/readme-template)  in your `htmlcss-branch`.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Adding a good page title in your `title` tag as indicated in the comment below.

I'm sure you gat this :muscle: Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 20:06 UTC, AbayomiOlaoye commented on index.html
> +    <title>Document</title>
- Well done, @ezraermy with a good job on this project :+1: 
- [ ] [OPTIONAL] It is a good practice to always use proper `html` semantics in your code. I think there's an omission with your `title` tag. It would a great idea as it's equally important to remove any trace of boiler codes or templates from your code base for good SEO ranking and crawling. This improves your page's accessibility. Kindly change the content within your `title` to that of your project. It allows `Seach Engines` to understand the purpose of your site compared with searched `keywords`.

2023-01-10 21:22 UTC, bienvenuushindi approved these changes
# STATUS: APPROVED 🟢 

## Hi @ezraermy   👋, 

Well done implementing the requested changes 👏
Your project is complete!  There is nothing else to say  :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/lJNoBCvQYp7nq/giphy.gif"/>

### Highlights 🎯 
:+1: No linter errors✔️
:+1: Good PR title

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 21:29 UTC, merged